import type { Application } from "@/types";

/**
 * Fictional participation applications.
 *
 * - `usr-01` (the mock current user) is both an applicant (app-01…05) and the
 *   owner of `init-06` / `init-13` (app-10…22 are received on those).
 * - app-30+ involve other users only; they exist for realism and are never
 *   shown to the current user.
 *
 * Timestamps sit around midday UTC so the rendered calendar day is the same
 * on the server and in any timezone from UTC-8 to UTC+11.
 */
export const applications: Application[] = [
  /* ---------------- Applications submitted BY the mock user ---------------- */
  {
    id: "app-01",
    initiativeId: "init-01",
    applicantId: "usr-01",
    role: "EXPERT",
    skills: ["تصميم حملات بيئية", "إدارة المشاريع البيئية"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message:
      "أعمل مهندسة بيئة ولدي تجربة في تنظيم حملات التنظيف والتشجير بالعاصمة. يسعدني تقديم استشارات حول تنظيم الحملات وتوعية السكان بأهمية الواحات.",
    supportingInfo: "شاركت في تنظيم أكثر من 10 حملات تطوعية بيئية منذ 2022.",
    status: "ACCEPTED",
    submittedAt: "2026-06-10T10:00:00.000Z",
    reviewedAt: "2026-06-12T11:30:00.000Z",
    reviewedById: "usr-06",
    reviewNote: "خبرتك في المشاريع البيئية ستفيد الفريق كثيرًا، مرحبًا بك مستشارة للحملة.",
    updatedAt: "2026-06-12T11:30:00.000Z",
  },
  {
    id: "app-02",
    initiativeId: "init-02",
    applicantId: "usr-01",
    role: "SUPPORTER",
    skills: ["تنسيق التبرعات"],
    availability: "FLEXIBLE",
    commitment: "ONE_TIME",
    message:
      "أرغب في المساهمة بجمع حواسيب محمولة مستعملة من الشركات والأصدقاء لصالح المتكونين غير الميسورين في وهران.",
    status: "PENDING",
    submittedAt: "2026-09-18T09:30:00.000Z",
    updatedAt: "2026-09-18T09:30:00.000Z",
  },
  {
    id: "app-03",
    initiativeId: "init-03",
    applicantId: "usr-01",
    role: "VOLUNTEER",
    skills: ["تنشيط الأطفال", "التواصل المجتمعي"],
    availability: "WEEKDAY_EVENINGS",
    commitment: "UNDER_2H",
    message:
      "أود التطوع في حصص الدعم المدرسي عن بُعد أو خلال زياراتي لقسنطينة، فأنا أحب العمل مع الأطفال وأتقن تبسيط المفاهيم العلمية.",
    status: "REJECTED",
    submittedAt: "2026-04-28T10:00:00.000Z",
    reviewedAt: "2026-05-02T12:00:00.000Z",
    reviewedById: "usr-03",
    reviewNote: "اكتمل عدد المتطوعين لهذه الدفعة، سنتواصل معك عند فتح دفعة جديدة.",
    updatedAt: "2026-05-02T12:00:00.000Z",
  },
  {
    id: "app-04",
    initiativeId: "init-05",
    applicantId: "usr-01",
    role: "EXPERT",
    skills: ["التسويق الرقمي", "بناء العلامات المحلية"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message:
      "يمكنني مرافقة التعاونيات النسائية في تسويق منتجاتها عبر الإنترنت وتصوير المنتجات وإنشاء صفحات بيع بسيطة.",
    status: "WITHDRAWN",
    submittedAt: "2026-05-14T10:00:00.000Z",
    withdrawnAt: "2026-05-20T13:00:00.000Z",
    withdrawnBy: "APPLICANT",
    updatedAt: "2026-05-20T13:00:00.000Z",
  },
  {
    id: "app-05",
    initiativeId: "init-04",
    applicantId: "usr-01",
    role: "VOLUNTEER",
    skills: ["التنسيق التطوعي", "التوعية الصحية"],
    availability: "CAMPAIGN_DAYS",
    commitment: "H5_TO_10",
    message:
      "أرغب في الانضمام إلى فريق تأطير يوم الحملة، لدي خبرة في تنظيم المتطوعين وتوزيع المهام في التظاهرات الميدانية.",
    status: "PENDING",
    submittedAt: "2026-09-22T09:00:00.000Z",
    updatedAt: "2026-09-22T09:00:00.000Z",
  },

  /* ------------- Applications received on init-06 (owned by usr-01) ------------- */
  {
    id: "app-10",
    initiativeId: "init-06",
    applicantId: "usr-08",
    role: "VOLUNTEER",
    skills: ["تنشيط الأطفال", "تنسيق الفرق الميدانية"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message:
      "أنشّط مخيمات للأطفال في عنابة وأودّ نقل هذه التجربة إلى حملات الغرس في العاصمة عند زياراتي، وتنظيم ورشات صغيرة للأطفال حول الأشجار.",
    supportingInfo: "يمكنني إحضار فريق من 5 مؤطرين شباب عند الحاجة.",
    status: "PENDING",
    submittedAt: "2026-09-21T10:00:00.000Z",
    updatedAt: "2026-09-21T10:00:00.000Z",
  },
  {
    id: "app-11",
    initiativeId: "init-06",
    applicantId: "usr-07",
    role: "EXPERT",
    skills: ["التصوير الفوتوغرافي", "توثيق المبادرات"],
    availability: "FLEXIBLE",
    commitment: "AS_NEEDED",
    message:
      "أعمل على توثيق التراث والمبادرات المحلية بالصور والفيديو، ويسعدني توثيق أيام الغرس وإنتاج مادة تعريفية تساعد على استقطاب المتطوعين.",
    status: "PENDING",
    submittedAt: "2026-09-23T11:00:00.000Z",
    updatedAt: "2026-09-23T11:00:00.000Z",
  },
  {
    id: "app-12",
    initiativeId: "init-06",
    applicantId: "usr-05",
    role: "PARTNER",
    skills: ["شراكات مع الجمعيات", "تنظيم الفعاليات"],
    availability: "FLEXIBLE",
    commitment: "AS_NEEDED",
    message:
      "تمثل جمعيتنا نساء ريفيات في تلمسان وتقترح شراكة لتبادل الخبرات في الزراعة وإشراك النساء في حملات الغرس.",
    status: "ACCEPTED",
    submittedAt: "2026-03-05T10:00:00.000Z",
    reviewedAt: "2026-03-07T10:30:00.000Z",
    reviewedById: "usr-01",
    reviewNote: "مرحبًا بالشراكة، سننسق معكم حول موعد الحملة القادمة.",
    updatedAt: "2026-03-07T10:30:00.000Z",
  },
  {
    id: "app-13",
    initiativeId: "init-06",
    applicantId: "usr-02",
    role: "VOLUNTEER",
    skills: ["إدارة الحسابات الرقمية", "التصميم البسيط"],
    availability: "WEEKDAY_EVENINGS",
    commitment: "UNDER_2H",
    message:
      "يمكنني إدارة صفحات المبادرة على مواقع التواصل وتصميم منشورات الحملات بشكل تطوعي خلال المساء.",
    status: "ACCEPTED",
    submittedAt: "2026-03-20T10:00:00.000Z",
    reviewedAt: "2026-03-21T09:00:00.000Z",
    reviewedById: "usr-01",
    reviewNote: "نحتاج فعلًا مساعدة رقمية، أهلًا بك في الفريق.",
    updatedAt: "2026-03-21T09:00:00.000Z",
  },
  {
    id: "app-14",
    initiativeId: "init-06",
    applicantId: "usr-09",
    role: "VOLUNTEER",
    skills: ["العمل الاجتماعي"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message:
      "أود المشاركة في حملات الغرس والتعريف بالمبادرة لدى العائلات التي أرافقها في باتنة.",
    status: "REJECTED",
    submittedAt: "2026-04-10T10:00:00.000Z",
    reviewedAt: "2026-04-12T10:00:00.000Z",
    reviewedById: "usr-01",
    reviewNote: "الحملات الميدانية تجري حاليًا في العاصمة فقط، نرحب بطلبك عند التوسع نحو باتنة.",
    updatedAt: "2026-04-12T10:00:00.000Z",
  },
  {
    id: "app-15",
    initiativeId: "init-06",
    applicantId: "usr-10",
    role: "SUPPORTER",
    skills: ["تمويل المشاريع الصغيرة"],
    availability: "FLEXIBLE",
    commitment: "ONE_TIME",
    message:
      "أرغب في التبرع بمئة شتلة من مشتلة أعرفها، وتغطية تكلفة نقلها إلى مواقع الغرس في العاصمة.",
    supportingInfo: "الشتلات من أنواع محلية مقاومة للجفاف (زيتون، خروب).",
    status: "PENDING",
    submittedAt: "2026-09-24T10:00:00.000Z",
    updatedAt: "2026-09-24T10:00:00.000Z",
  },
  {
    id: "app-16",
    initiativeId: "init-06",
    applicantId: "usr-04",
    role: "VOLUNTEER",
    skills: ["الإسعافات الأولية"],
    availability: "CAMPAIGN_DAYS",
    commitment: "UNDER_2H",
    message:
      "أستطيع تأمين الإسعافات الأولية خلال أيام الغرس الكبرى بصفتي طبيبًا عامًا، على أن يكون ذلك في نهاية الأسبوع.",
    status: "WITHDRAWN",
    submittedAt: "2026-05-02T10:00:00.000Z",
    withdrawnAt: "2026-05-05T10:00:00.000Z",
    withdrawnBy: "APPLICANT",
    updatedAt: "2026-05-05T10:00:00.000Z",
  },
  {
    id: "app-17",
    initiativeId: "init-06",
    applicantId: "usr-03",
    role: "EXPERT",
    skills: ["التربية البيئية", "إعداد الورشات للأطفال"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message:
      "بصفتي معلمة، أستطيع إعداد ورشات تربوية قصيرة تشرح للأطفال أهمية الأشجار ودورة الماء، وتدريب المتطوعين على تبسيطها.",
    status: "ACCEPTED",
    submittedAt: "2026-04-22T10:00:00.000Z",
    reviewedAt: "2026-04-23T10:00:00.000Z",
    reviewedById: "usr-01",
    reviewNote: "إضافة رائعة للجانب التوعوي، شكرًا لك.",
    updatedAt: "2026-04-23T10:00:00.000Z",
  },

  /* ------------- Applications received on init-13 (owned by usr-01) ------------- */
  {
    id: "app-20",
    initiativeId: "init-13",
    applicantId: "usr-04",
    role: "EXPERT",
    skills: ["الطب العام", "التوعية الصحية"],
    availability: "WEEKDAY_EVENINGS",
    commitment: "UNDER_2H",
    message:
      "بصفتي طبيبًا عامًا يمكنني تقديم جلسات توعية حول الضغط الدراسي وعلاقته بالصحة الجسدية وتوجيه الطلبة إلى المختصين.",
    status: "ACCEPTED",
    submittedAt: "2025-12-05T10:00:00.000Z",
    reviewedAt: "2025-12-07T10:00:00.000Z",
    reviewedById: "usr-01",
    reviewNote: "مرحبًا بك مستشارًا صحيًا للمبادرة.",
    updatedAt: "2025-12-07T10:00:00.000Z",
  },
  {
    id: "app-21",
    initiativeId: "init-13",
    applicantId: "usr-08",
    role: "VOLUNTEER",
    skills: ["التنشيط الجماعي"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message:
      "أرغب في المساعدة على تنشيط ورشات الاسترخاء الجماعي للطلبة وتنظيم أنشطة رياضية خفيفة لتخفيف الضغط.",
    status: "PENDING",
    submittedAt: "2026-07-02T10:00:00.000Z",
    updatedAt: "2026-07-02T10:00:00.000Z",
  },
  {
    id: "app-22",
    initiativeId: "init-13",
    applicantId: "usr-06",
    role: "SUPPORTER",
    skills: ["توفير قاعات"],
    availability: "FLEXIBLE",
    commitment: "ONE_TIME",
    message:
      "أستطيع توفير قاعة اجتماعات لمدة شهرين مجانًا لتنظيم ورشات المبادرة عند استئناف نشاطها.",
    status: "REJECTED",
    submittedAt: "2026-06-25T10:00:00.000Z",
    reviewedAt: "2026-06-27T10:00:00.000Z",
    reviewedById: "usr-01",
    reviewNote: "المبادرة متوقفة مؤقتًا، سنعاود التواصل معك بمجرد استئناف النشاط. شكرًا لعرضك الكريم.",
    updatedAt: "2026-06-27T10:00:00.000Z",
  },

  /* ---------- Applications between other users (never shown to usr-01) ---------- */
  {
    id: "app-30",
    initiativeId: "init-01",
    applicantId: "usr-08",
    role: "VOLUNTEER",
    skills: ["تنسيق الفرق الميدانية"],
    availability: "WEEKENDS",
    commitment: "H2_TO_5",
    message: "أرغب في المشاركة في حملات تنظيف الواحات خلال نهاية الأسبوع وتنسيق مجموعات من الشباب.",
    status: "PENDING",
    submittedAt: "2026-09-15T10:00:00.000Z",
    updatedAt: "2026-09-15T10:00:00.000Z",
  },
  {
    id: "app-31",
    initiativeId: "init-02",
    applicantId: "usr-03",
    role: "EXPERT",
    skills: ["بيداغوجيا", "تصميم دروس"],
    availability: "WEEKDAY_EVENINGS",
    commitment: "H2_TO_5",
    message: "يمكنني مساعدة المدربين في تبسيط الدروس وإعداد مسار تعلم مناسب للمبتدئين.",
    status: "ACCEPTED",
    submittedAt: "2026-06-02T10:00:00.000Z",
    reviewedAt: "2026-06-03T10:00:00.000Z",
    reviewedById: "usr-02",
    reviewNote: "أهلًا بك في فريق المدربين.",
    updatedAt: "2026-06-03T10:00:00.000Z",
  },
  {
    id: "app-32",
    initiativeId: "init-07",
    applicantId: "usr-05",
    role: "SUPPORTER",
    skills: ["جمع التبرعات"],
    availability: "FLEXIBLE",
    commitment: "ONE_TIME",
    message: "أود التبرع بمجموعة ملابس أطفال جديدة جمعتها جمعيتنا بتلمسان لصالح حملة كسوة العيد.",
    status: "PENDING",
    submittedAt: "2026-09-19T10:00:00.000Z",
    updatedAt: "2026-09-19T10:00:00.000Z",
  },
  {
    id: "app-33",
    initiativeId: "init-14",
    applicantId: "usr-02",
    role: "EXPERT",
    skills: ["تطوير الويب", "التدريب"],
    availability: "WEEKENDS",
    commitment: "H5_TO_10",
    message: "لدي خبرة في تدريس البرمجة للمبتدئين وأرغب في المشاركة كمدرب في المعسكر.",
    status: "REJECTED",
    submittedAt: "2026-09-08T10:00:00.000Z",
    reviewedAt: "2026-09-09T10:00:00.000Z",
    reviewedById: "usr-04",
    reviewNote: "تعارض موعد المعسكر مع التزاماتك المذكورة، شكرًا لاهتمامك.",
    updatedAt: "2026-09-09T10:00:00.000Z",
  },
];
