import type { Initiative } from "@/types";

/**
 * Fictional initiatives spanning all categories, several wilayas and every
 * status value. This is the dataset the service layer reads from; when a
 * real backend exists, `lib/services/initiative-service.ts` will query
 * Postgres/Prisma instead and this file can be deleted.
 */
export const initiatives: Initiative[] = [
  {
    id: "init-01",
    slug: "tandhif-wahat-el-oued",
    title: "تنظيف وترميم واحات الوادي",
    shortDescription: "حملة جماعية لتنظيف النخيل والسواقي التقليدية من النفايات البلاستيكية.",
    description:
      "تستهدف هذه المبادرة تنظيف الواحات التقليدية بولاية الوادي من النفايات المتراكمة، وإعادة تأهيل السواقي (الفقارة) التي تعاني من الانسداد. يشارك في الحملة متطوعون من الأحياء المجاورة، بالتنسيق مع الفلاحين المحليين، مع تنظيم ورشات توعوية حول أهمية الحفاظ على النظام البيئي الواحي.",
    categorySlug: "environment",
    wilayaSlug: "el-oued",
    status: "active",
    organizerId: "usr-06",
    membersCount: 128,
    featured: true,
    tags: ["بيئة", "واحات", "تطوع"],
    createdAt: "2026-06-02",
    updatedAt: "2026-09-10",
    needs: [
      {
        id: "n-01-1",
        type: "volunteers",
        title: "متطوعون لأيام التنظيف الميدانية",
        description: "المشاركة في جلسات تنظيف كل نهاية أسبوع.",
        quantityNeeded: 200,
        quantityFulfilled: 128,
        unit: "متطوع",
      },
      {
        id: "n-01-2",
        type: "equipment",
        title: "أدوات تنظيف وقفازات",
        quantityNeeded: 300,
        quantityFulfilled: 150,
        unit: "قطعة",
      },
    ],
    opportunities: [
      {
        id: "opp-01-volunteer",
        role: "VOLUNTEER",
        title: "متطوع تنظيف ميداني",
        description: "المشاركة في جلسات تنظيف الواحات والسواقي كل نهاية أسبوع.",
        requiredSkills: ["العمل الجماعي", "اللياقة البدنية"],
        commitment: "4 ساعات كل أسبوع تقريبًا",
      },
      {
        id: "opp-01-expert",
        role: "EXPERT",
        title: "مستشار في البيئة الواحية",
        description: "تقديم استشارة حول حماية النخيل والنظام البيئي الواحي وتدريب المتطوعين.",
        requiredSkills: ["علوم البيئة", "الفلاحة الواحية"],
        commitment: "جلسة استشارية شهرية",
      },
      {
        id: "opp-01-supporter",
        role: "SUPPORTER",
        title: "داعم بالأدوات والتجهيزات",
        description: "توفير قفازات وأكياس وأدوات تنظيف للحملات القادمة.",
        requiredSkills: [],
        commitment: "مساهمة لمرة واحدة أو دورية",
      },
    ],
  },
  {
    id: "init-02",
    slug: "tadrib-rakmi-shabab-wahran",
    title: "تكوين رقمي مجاني لشباب وهران",
    shortDescription: "دورات مجانية في تطوير الويب وتحليل البيانات لفائدة الشباب الباحثين عن عمل.",
    description:
      "مبادرة تهدف إلى تقليص الفجوة الرقمية لدى شباب وهران غير الملتحقين بالجامعة، عبر تنظيم دورات تكوينية مسائية في تطوير الويب، تحليل البيانات، والتسويق الرقمي، بإشراف مطورين ومهندسين متطوعين من سوق العمل المحلي.",
    categorySlug: "technology",
    wilayaSlug: "oran",
    status: "active",
    organizerId: "usr-02",
    membersCount: 210,
    featured: true,
    tags: ["تكوين", "برمجة", "تشغيل"],
    createdAt: "2026-05-20",
    updatedAt: "2026-09-15",
    needs: [
      {
        id: "n-02-1",
        type: "skills",
        title: "مدربون في تطوير الويب وتحليل البيانات",
        quantityNeeded: 15,
        quantityFulfilled: 9,
        unit: "مدرب",
      },
      {
        id: "n-02-2",
        type: "equipment",
        title: "حواسيب محمولة للمتكونين غير الميسورين",
        quantityNeeded: 25,
        quantityFulfilled: 11,
        unit: "حاسوب",
      },
    ],
    opportunities: [
      {
        id: "opp-02-expert",
        role: "EXPERT",
        title: "مدرب تطوير ويب وتحليل بيانات",
        description: "تقديم حصص مسائية للمتكونين وفق برنامج تدريبي واضح.",
        requiredSkills: ["تطوير الويب", "تحليل البيانات", "التدريب"],
        commitment: "حصة أسبوعية من ساعتين",
      },
      {
        id: "opp-02-supporter",
        role: "SUPPORTER",
        title: "داعم بحواسيب محمولة",
        description: "التبرع بحواسيب مستعملة صالحة للاستعمال للمتكونين غير الميسورين.",
        requiredSkills: [],
        commitment: "مساهمة لمرة واحدة",
      },
      {
        id: "opp-02-partner",
        role: "PARTNER",
        title: "شريك مؤسساتي",
        description: "شركات ومراكز تكوين تستضيف الدورات أو توفر فرص تدريب للمتكونين.",
        requiredSkills: [],
        commitment: "اتفاقية شراكة وتنسيق دوري",
      },
    ],
  },
  {
    id: "init-03",
    slug: "dars-taqwiya-atfal-qacentina",
    title: "دروس دعم مدرسي لأطفال الأحياء الشعبية",
    shortDescription: "مرافقة دراسية مجانية لتلاميذ الابتدائي والمتوسط في أحياء قسنطينة الشعبية.",
    description:
      "تنظم هذه المبادرة حصص دعم مدرسي أسبوعية في مادتي الرياضيات واللغة العربية لفائدة تلاميذ الأحياء الشعبية بقسنطينة، بمساعدة طلبة جامعيين متطوعين، بهدف تقليص الفوارق التعليمية وتحسين نتائج التلاميذ في المراحل الحاسمة.",
    categorySlug: "education",
    wilayaSlug: "constantine",
    status: "active",
    organizerId: "usr-03",
    membersCount: 96,
    featured: true,
    tags: ["تعليم", "دعم مدرسي", "تطوع"],
    createdAt: "2026-04-15",
    updatedAt: "2026-09-01",
    needs: [
      {
        id: "n-03-1",
        type: "volunteers",
        title: "طلبة متطوعون لتقديم الدروس",
        quantityNeeded: 40,
        quantityFulfilled: 27,
        unit: "متطوع",
      },
      {
        id: "n-03-2",
        type: "donations",
        title: "أدوات مدرسية للتلاميذ المحتاجين",
        quantityNeeded: 500000,
        quantityFulfilled: 210000,
        unit: "دج",
      },
    ],
    opportunities: [
      {
        id: "opp-03-volunteer",
        role: "VOLUNTEER",
        title: "متطوع دعم مدرسي",
        description: "تقديم حصص أسبوعية في الرياضيات واللغة العربية لتلاميذ الأحياء الشعبية.",
        requiredSkills: ["الرياضيات", "اللغة العربية", "التواصل مع الأطفال"],
        commitment: "ساعتان أسبوعيًا",
      },
      {
        id: "opp-03-supporter",
        role: "SUPPORTER",
        title: "داعم بالأدوات المدرسية",
        description: "التبرع بمحافظ وكراريس وأدوات هندسية للتلاميذ المحتاجين.",
        requiredSkills: [],
        commitment: "مساهمة لمرة واحدة",
      },
    ],
  },
  {
    id: "init-04",
    slug: "hamlat-tabarru-bil-dam-setif",
    title: "حملة التبرع بالدم بسطيف",
    shortDescription: "حملة تحسيسية وميدانية للتبرع بالدم بالتنسيق مع مستشفى الولاية.",
    description:
      "بالتنسيق مع مصلحة نقل الدم بمستشفى سطيف، تنظم هذه المبادرة حملة تبرع بالدم مصحوبة بقافلة توعوية في الجامعات والثانويات، لسد النقص المسجل خلال فصل الصيف وتشجيع ثقافة التبرع المنتظم بالدم.",
    categorySlug: "health",
    wilayaSlug: "setif",
    status: "upcoming",
    organizerId: "usr-04",
    membersCount: 64,
    featured: true,
    tags: ["صحة", "تبرع بالدم"],
    createdAt: "2026-08-25",
    updatedAt: "2026-09-20",
    needs: [
      {
        id: "n-04-1",
        type: "volunteers",
        title: "متطوعون لتأطير يوم الحملة",
        quantityNeeded: 30,
        quantityFulfilled: 12,
        unit: "متطوع",
      },
      {
        id: "n-04-2",
        type: "partnership",
        title: "شراكة مع مؤسسات ومدارس محلية",
        quantityNeeded: 10,
        quantityFulfilled: 3,
        unit: "مؤسسة",
      },
    ],
    opportunities: [
      {
        id: "opp-04-volunteer",
        role: "VOLUNTEER",
        title: "متطوع تأطير يوم الحملة",
        description: "المساعدة في استقبال المتبرعين وتنظيم الطوابير وتوزيع المطويات التوعوية.",
        requiredSkills: ["التنظيم", "التواصل مع الجمهور"],
        commitment: "يوم كامل + تحضير قصير قبل الحملة",
      },
      {
        id: "opp-04-partner",
        role: "PARTNER",
        title: "شريك من مؤسسة أو مدرسة",
        description: "استضافة قافلة التوعية أو التعريف بالحملة لدى الطلبة والموظفين.",
        requiredSkills: [],
        commitment: "تنسيق قبل الحملة بأسبوعين",
      },
    ],
  },
  {
    id: "init-05",
    slug: "tamkin-nisaa-rifiyat-tlemcen",
    title: "تمكين النساء الريفيات اقتصاديًا بتلمسان",
    shortDescription: "تكوين النساء الريفيات على الخياطة والتحويل الغذائي وتسويق منتجاتهن.",
    description:
      "تستهدف المبادرة النساء الريفيات بضواحي تلمسان، عبر تكوينات في الخياطة التقليدية والتحويل الغذائي، إلى جانب مرافقة إدارية لتأسيس تعاونيات صغيرة وتسويق المنتجات محليًا وعبر الإنترنت.",
    categorySlug: "women",
    wilayaSlug: "tlemcen",
    status: "active",
    organizerId: "usr-05",
    membersCount: 74,
    featured: true,
    tags: ["تمكين المرأة", "تعاونيات"],
    createdAt: "2026-03-10",
    updatedAt: "2026-08-28",
    needs: [
      {
        id: "n-05-1",
        type: "skills",
        title: "مكونات في التحويل الغذائي والتسويق",
        quantityNeeded: 8,
        quantityFulfilled: 5,
        unit: "مكونة",
      },
      {
        id: "n-05-2",
        type: "equipment",
        title: "آلات خياطة وتعبئة",
        quantityNeeded: 20,
        quantityFulfilled: 14,
        unit: "آلة",
      },
    ],
    opportunities: [
      {
        id: "opp-05-expert",
        role: "EXPERT",
        title: "مكوّن في التحويل الغذائي والتسويق",
        description: "مرافقة النساء في التعاونيات في إنتاج وتسويق منتجاتهن.",
        requiredSkills: ["التحويل الغذائي", "التسويق الرقمي"],
        commitment: "ساعتان كل أسبوعين",
      },
      {
        id: "opp-05-supporter",
        role: "SUPPORTER",
        title: "داعم بمعدات",
        description: "التبرع بآلات خياطة أو تعبئة أو ماكينات صغيرة صالحة للعمل.",
        requiredSkills: [],
        commitment: "مساهمة لمرة واحدة",
      },
      {
        id: "opp-05-partner",
        role: "PARTNER",
        title: "شريك تسويقي",
        description: "محلات وجمعيات تفتح منافذ عرض وبيع لمنتجات التعاونيات.",
        requiredSkills: [],
        commitment: "اتفاقية تعاون دورية",
      },
    ],
  },
  {
    id: "init-06",
    slug: "tashjir-hadaeq-el-jazaer",
    title: "حملة تشجير حدائق أحياء العاصمة",
    shortDescription: "غرس أشجار محلية في الحدائق العمومية وتحسيس السكان بالحفاظ عليها.",
    description:
      "بالشراكة مع بلديات عدة بالعاصمة، تعمل هذه المبادرة على غرس أشجار وشجيرات محلية الأصل في الحدائق والفضاءات العمومية المهملة، مع تنظيم أيام توعوية للأطفال حول أهمية المساحات الخضراء الحضرية.",
    categorySlug: "environment",
    wilayaSlug: "alger",
    status: "active",
    organizerId: "usr-01",
    membersCount: 152,
    featured: false,
    tags: ["بيئة", "تشجير"],
    createdAt: "2026-02-18",
    updatedAt: "2026-09-05",
    targetAudience: "سكان الأحياء وأطفال المدارس والجمعيات المحلية",
    goals: [
      "غرس ألف شتلة محلية الأصل خلال الموسم",
      "إشراك 150 متطوعًا في أيام الغرس",
      "تنظيم ورشات توعوية للأطفال حول المساحات الخضراء",
    ],
    requiredSkills: ["البستنة", "التنسيق الميداني"],
    startDate: "2026-02-25",
    needs: [
      {
        id: "n-06-1",
        type: "donations",
        title: "شتلات أشجار محلية",
        quantityNeeded: 1000,
        quantityFulfilled: 640,
        unit: "شتلة",
      },
      {
        id: "n-06-2",
        type: "volunteers",
        title: "متطوعون لأيام الغرس",
        quantityNeeded: 150,
        quantityFulfilled: 152,
        unit: "متطوع",
      },
    ],
    opportunities: [
      {
        id: "opp-06-volunteer",
        role: "VOLUNTEER",
        title: "متطوع غرس ميداني",
        description: "المشاركة في أيام الغرس وسقي الشتلات ومتابعتها في الأحياء.",
        requiredSkills: ["العمل الجماعي", "اللياقة البدنية"],
        commitment: "4 ساعات كل أسبوعين تقريبًا",
      },
      {
        id: "opp-06-expert",
        role: "EXPERT",
        title: "مستشار بستنة وبيئة",
        description: "اقتراح الأنواع المحلية المناسبة وتدريب المتطوعين على الغرس الصحيح.",
        requiredSkills: ["البستنة", "علوم البيئة"],
        commitment: "جلسة استشارية شهرية",
      },
      {
        id: "opp-06-partner",
        role: "PARTNER",
        title: "شريك مؤسساتي",
        description: "بلديات وجمعيات ومؤسسات تساهم في توفير المساحات والشتلات والتنسيق.",
        requiredSkills: [],
        commitment: "اتفاقية شراكة وتنسيق دوري",
      },
      {
        id: "opp-06-supporter",
        role: "SUPPORTER",
        title: "داعم بالشتلات أو التمويل",
        description: "التبرع بشتلات محلية أو تغطية مصاريف النقل والسقي.",
        requiredSkills: [],
        commitment: "مساهمة لمرة واحدة أو دورية",
      },
    ],
  },
  {
    id: "init-07",
    slug: "kiswat-al-eid-batna",
    title: "كسوة العيد لعائلات باتنة المحتاجة",
    shortDescription: "جمع وتوزيع ملابس وألعاب جديدة لأطفال العائلات المعوزة قبل العيد.",
    description:
      "مبادرة تضامنية سنوية تجمع تبرعات نقدية وعينية لشراء كسوة العيد وألعاب للأطفال من العائلات المحتاجة بريف باتنة، مع توزيع مباشر على العائلات المستفادة بالتنسيق مع الخلايا الاجتماعية بالبلديات.",
    categorySlug: "solidarity",
    wilayaSlug: "batna",
    status: "active",
    organizerId: "usr-09",
    membersCount: 187,
    featured: true,
    tags: ["تضامن", "كسوة العيد"],
    createdAt: "2026-07-01",
    updatedAt: "2026-09-18",
    needs: [
      {
        id: "n-07-1",
        type: "donations",
        title: "تبرعات نقدية لشراء الكسوة",
        quantityNeeded: 800000,
        quantityFulfilled: 512000,
        unit: "دج",
      },
      {
        id: "n-07-2",
        type: "volunteers",
        title: "متطوعون للفرز والتوزيع",
        quantityNeeded: 25,
        quantityFulfilled: 20,
        unit: "متطوع",
      },
    ],
  },
  {
    id: "init-08",
    slug: "mukhayyam-sayfi-annaba",
    title: "مخيم صيفي لأطفال الأحياء الشعبية بعنابة",
    shortDescription: "مخيم ترفيهي وتربوي مجاني لمدة أسبوع لأطفال الأحياء المحرومة.",
    description:
      "ينظم فريق من المدربين الشباب مخيمًا صيفيًا مجانيًا لأطفال الأحياء الشعبية بعنابة، يجمع بين الأنشطة الرياضية والفنية وورشات التوعية، بهدف توفير فضاء آمن وهادف خلال العطلة الصيفية.",
    categorySlug: "sports",
    wilayaSlug: "annaba",
    status: "upcoming",
    organizerId: "usr-08",
    membersCount: 58,
    featured: false,
    tags: ["شباب", "رياضة", "مخيم"],
    createdAt: "2026-09-01",
    updatedAt: "2026-09-22",
    needs: [
      {
        id: "n-08-1",
        type: "volunteers",
        title: "مؤطرون ومدربون رياضيون",
        quantityNeeded: 20,
        quantityFulfilled: 8,
        unit: "مؤطر",
      },
      {
        id: "n-08-2",
        type: "equipment",
        title: "معدات رياضية وأدوات فنية",
        quantityNeeded: 15,
        quantityFulfilled: 4,
        unit: "قطعة",
      },
    ],
  },
  {
    id: "init-09",
    slug: "tawthiq-turath-bejaia",
    title: "توثيق التراث الشفوي والمعماري ببجاية",
    shortDescription: "جمع وتوثيق الحكايات الشعبية والمعمار التقليدي لقرى بجاية قبل اندثاره.",
    description:
      "يعمل فريق من الباحثين الشباب على توثيق الحكايات الشعبية والأغاني التقليدية والمعمار القديم لقرى منطقة بجاية عبر تسجيلات صوتية ومرئية وأرشيف صور، لإنشاء قاعدة بيانات ثقافية مفتوحة للأجيال القادمة.",
    categorySlug: "culture",
    wilayaSlug: "bejaia",
    status: "active",
    organizerId: "usr-07",
    membersCount: 41,
    featured: false,
    tags: ["تراث", "توثيق", "ثقافة"],
    createdAt: "2026-01-22",
    updatedAt: "2026-08-30",
    needs: [
      {
        id: "n-09-1",
        type: "skills",
        title: "متطوعون بمهارات تصوير وتحرير فيديو",
        quantityNeeded: 6,
        quantityFulfilled: 3,
        unit: "متطوع",
      },
      {
        id: "n-09-2",
        type: "equipment",
        title: "معدات تسجيل صوتي ومرئي",
        quantityNeeded: 5,
        quantityFulfilled: 2,
        unit: "قطعة",
      },
    ],
  },
  {
    id: "init-10",
    slug: "murafaqat-mubadirin-ghardaia",
    title: "مرافقة حاملي المشاريع الصغيرة بغرداية",
    shortDescription: "تكوين ومرافقة إدارية ومالية لشباب الجنوب لإطلاق مشاريعهم الصغيرة.",
    description:
      "مبادرة تجمع رواد أعمال متمرسين لمرافقة شباب ولاية غرداية الراغبين في إطلاق مشاريع صغيرة في الحرف والفلاحة والتجارة، عبر ورشات في إعداد دراسة الجدوى، التمويل الأصغر، والتسويق المحلي.",
    categorySlug: "employment",
    wilayaSlug: "ghardaia",
    status: "active",
    organizerId: "usr-10",
    membersCount: 53,
    featured: false,
    tags: ["ريادة أعمال", "تشغيل"],
    createdAt: "2026-05-05",
    updatedAt: "2026-09-12",
    needs: [
      {
        id: "n-10-1",
        type: "skills",
        title: "مرافقون في التسيير المالي والإداري",
        quantityNeeded: 10,
        quantityFulfilled: 6,
        unit: "مرافق",
      },
      {
        id: "n-10-2",
        type: "partnership",
        title: "شراكة مع هيئات دعم التشغيل",
        quantityNeeded: 5,
        quantityFulfilled: 2,
        unit: "هيئة",
      },
    ],
  },
  {
    id: "init-11",
    slug: "nadi-al-qiraa-wahran",
    title: "نادي القراءة الحر بوهران",
    shortDescription: "لقاءات أسبوعية لمناقشة الكتب وتشجيع الشباب على القراءة.",
    description:
      "نادي مجتمعي أسبوعي جمع عشاق القراءة بوهران لمناقشة أعمال أدبية وفكرية متنوعة، ونظّم على مدار سنة كاملة أكثر من 40 لقاءً وسوق كتاب مستعمل لصالح مكتبات الأحياء الشعبية قبل أن يختتم نسخته الأولى بنجاح.",
    categorySlug: "education",
    wilayaSlug: "oran",
    status: "completed",
    organizerId: "usr-02",
    membersCount: 133,
    featured: false,
    tags: ["قراءة", "ثقافة"],
    createdAt: "2025-01-10",
    updatedAt: "2026-01-05",
    needs: [
      {
        id: "n-11-1",
        type: "donations",
        title: "كتب مستعملة للتبرع بها للمكتبات",
        quantityNeeded: 600,
        quantityFulfilled: 600,
        unit: "كتاب",
      },
    ],
  },
  {
    id: "init-12",
    slug: "tandhif-shawati-annaba",
    title: "تنظيف شواطئ عنابة",
    shortDescription: "حملة صيفية موسّعة لتنظيف الشواطئ وتحسيس المصطافين بالفرز.",
    description:
      "على مدار موسم الاصطياف، نظّم متطوعو المبادرة حملات تنظيف أسبوعية لشواطئ عنابة، وزّعوا خلالها أكياس فرز النفايات وقاموا بورشات توعية للمصطافين، قبل اختتام الموسم بحصيلة إيجابية وتعهدات من البلدية بمواصلة الجهد.",
    categorySlug: "environment",
    wilayaSlug: "annaba",
    status: "completed",
    organizerId: "usr-08",
    membersCount: 210,
    featured: false,
    tags: ["بيئة", "شواطئ"],
    createdAt: "2025-06-01",
    updatedAt: "2025-09-15",
    needs: [
      {
        id: "n-12-1",
        type: "volunteers",
        title: "متطوعون لأيام التنظيف",
        quantityNeeded: 200,
        quantityFulfilled: 210,
        unit: "متطوع",
      },
    ],
  },
  {
    id: "init-13",
    slug: "tawaia-siha-nafsiya-el-jazaer",
    title: "التوعية بالصحة النفسية لطلبة الجامعات",
    shortDescription: "ورشات وجلسات استماع للتحسيس بأهمية الصحة النفسية لدى الطلبة.",
    description:
      "أطلقت المبادرة سلسلة ورشات توعوية داخل الحرم الجامعي حول الصحة النفسية وإدارة الضغط الدراسي، بمرافقة أخصائيين نفسانيين متطوعين، قبل أن تتوقف مؤقتًا لإعادة هيكلة الفريق وتأمين تمويل إضافي لمواصلة النشاط.",
    categorySlug: "health",
    wilayaSlug: "alger",
    status: "paused",
    organizerId: "usr-01",
    membersCount: 37,
    featured: false,
    tags: ["صحة نفسية", "طلبة"],
    createdAt: "2025-11-12",
    updatedAt: "2026-06-20",
    targetAudience: "طلبة الجامعات والإقامات الجامعية",
    goals: [
      "تنظيم ورشات شهرية حول إدارة الضغط الدراسي",
      "توفير جلسات استماع مجانية مع أخصائيين",
    ],
    requiredSkills: ["علم النفس", "التنشيط الجماعي"],
    startDate: "2025-12-01",
    needs: [
      {
        id: "n-13-1",
        type: "skills",
        title: "أخصائيون نفسانيون متطوعون",
        quantityNeeded: 6,
        quantityFulfilled: 2,
        unit: "أخصائي",
      },
      {
        id: "n-13-2",
        type: "donations",
        title: "تمويل لاستئجار قاعات الورشات",
        quantityNeeded: 150000,
        quantityFulfilled: 40000,
        unit: "دج",
      },
    ],
    opportunities: [
      {
        id: "opp-13-volunteer",
        role: "VOLUNTEER",
        title: "متطوع تنشيط ورشات",
        description: "المساعدة في تنظيم ورشات الاسترخاء والحوار داخل الحرم الجامعي.",
        requiredSkills: ["التنشيط الجماعي", "الإنصات"],
        commitment: "3 ساعات شهريًا",
      },
      {
        id: "opp-13-expert",
        role: "EXPERT",
        title: "أخصائي نفسي أو صحي",
        description: "تقديم جلسات استماع وتوعية وتوجيه الطلبة نحو المختصين.",
        requiredSkills: ["علم النفس", "التوعية الصحية"],
        commitment: "جلسة شهرية",
      },
      {
        id: "opp-13-supporter",
        role: "SUPPORTER",
        title: "داعم بقاعات أو تمويل",
        description: "توفير فضاءات لتنظيم الورشات أو المساهمة في تكاليفها.",
        requiredSkills: [],
        commitment: "مساهمة لمرة واحدة",
      },
    ],
  },
  {
    id: "init-14",
    slug: "muaskar-barmaja-shabab-setif",
    title: "معسكر برمجة لشباب سطيف",
    shortDescription: "معسكر تكويني مكثف في أساسيات البرمجة لفائدة تلاميذ الثانوي.",
    description:
      "معسكر تكويني مكثف مدته أسبوعان، يقدم لتلاميذ الثانوي بولاية سطيف مدخلاً عمليًا لأساسيات البرمجة وبناء مشاريع صغيرة، بإشراف مهندسين متطوعين، تحضيرًا لمسابقة وطنية للمشاريع الرقمية الشبابية.",
    categorySlug: "technology",
    wilayaSlug: "setif",
    status: "upcoming",
    organizerId: "usr-04",
    membersCount: 45,
    featured: false,
    tags: ["برمجة", "شباب", "تكوين"],
    createdAt: "2026-09-05",
    updatedAt: "2026-09-24",
    needs: [
      {
        id: "n-14-1",
        type: "skills",
        title: "مدربون في البرمجة",
        quantityNeeded: 8,
        quantityFulfilled: 3,
        unit: "مدرب",
      },
      {
        id: "n-14-2",
        type: "equipment",
        title: "حواسيب للتدريب",
        quantityNeeded: 20,
        quantityFulfilled: 7,
        unit: "حاسوب",
      },
    ],
  },
  {
    id: "init-15",
    slug: "souq-khayri-tlemcen",
    title: "السوق الخيري لدعم العائلات المحتاجة بتلمسان",
    shortDescription: "سوق شهري لبيع منتجات محلية بأسعار رمزية وتوجيه العائد لعائلات محتاجة.",
    description:
      "سوق تضامني شهري ينظم في ساحة عمومية بتلمسان، تُعرض فيه منتجات غذائية وحرفية محلية بأسعار رمزية، ويوجَّه كامل العائد لدعم عائلات محتاجة تم تحديدها بالتنسيق مع جمعيات الحي.",
    categorySlug: "solidarity",
    wilayaSlug: "tlemcen",
    status: "active",
    organizerId: "usr-05",
    membersCount: 89,
    featured: false,
    tags: ["تضامن", "سوق خيري"],
    createdAt: "2026-03-28",
    updatedAt: "2026-09-08",
    needs: [
      {
        id: "n-15-1",
        type: "donations",
        title: "منتجات غذائية وحرفية للعرض بالسوق",
        quantityNeeded: 200,
        quantityFulfilled: 130,
        unit: "منتج",
      },
      {
        id: "n-15-2",
        type: "volunteers",
        title: "متطوعون لتسيير أكشاك السوق",
        quantityNeeded: 20,
        quantityFulfilled: 14,
        unit: "متطوع",
      },
    ],
  },
  {
    id: "init-16",
    slug: "tamkin-fallahat-el-oued",
    title: "تمكين الفلاحات الواحيات بالوادي",
    shortDescription: "تكوين النساء الفلاحات على تثمين منتجات النخيل وتسويقها.",
    description:
      "تستعد هذه المبادرة لإطلاق برنامج تكويني للفلاحات بولاية الوادي حول تثمين منتجات النخيل (التمور الثانوية، الخل، مواد التجميل الطبيعية) وتسويقها عبر منصات رقمية، بالشراكة مع تعاونية فلاحية محلية.",
    categorySlug: "women",
    wilayaSlug: "el-oued",
    status: "upcoming",
    organizerId: "usr-06",
    membersCount: 22,
    featured: false,
    tags: ["تمكين المرأة", "فلاحة", "نخيل"],
    createdAt: "2026-09-10",
    updatedAt: "2026-09-25",
    needs: [
      {
        id: "n-16-1",
        type: "skills",
        title: "مكونات في تثمين وتغليف منتجات النخيل",
        quantityNeeded: 5,
        quantityFulfilled: 1,
        unit: "مكونة",
      },
      {
        id: "n-16-2",
        type: "partnership",
        title: "شراكة مع تعاونيات فلاحية",
        quantityNeeded: 3,
        quantityFulfilled: 1,
        unit: "تعاونية",
      },
    ],
  },
];
