import type { Notification } from "@/types";

/**
 * Notifications addressed to the demo user (usr-01, who owns init-06 and init-13
 * and has also applied to other initiatives). Unread ones have no `readAt`.
 * Every entry mirrors something that exists elsewhere in the mock data
 * (an application, a conversation, an initiative).
 */
export const notifications: Notification[] = [
  {
    id: "ntf-01",
    userId: "usr-01",
    type: "APPLICATION_RECEIVED",
    title: "طلب انضمام جديد",
    message: 'أرسل توفيق بن عيسى طلبًا للانضمام إلى "حملة تشجير حدائق أحياء العاصمة" بصفة داعم.',
    createdAt: "2026-09-24T10:05:00.000Z",
    href: "/dashboard/initiatives/init-06/applications",
    actorId: "usr-10",
    initiativeId: "init-06",
    applicationId: "app-15",
  },
  {
    id: "ntf-02",
    userId: "usr-01",
    type: "APPLICATION_RECEIVED",
    title: "طلب انضمام جديد",
    message: 'أرسلت نور الهدى زروقي طلبًا للانضمام إلى "حملة تشجير حدائق أحياء العاصمة" بصفة خبير / مستشار.',
    createdAt: "2026-09-23T11:05:00.000Z",
    href: "/dashboard/initiatives/init-06/applications",
    actorId: "usr-07",
    initiativeId: "init-06",
    applicationId: "app-11",
  },
  {
    id: "ntf-03",
    userId: "usr-01",
    type: "APPLICATION_RECEIVED",
    title: "طلب انضمام جديد",
    message: 'أرسل إسلام حمدي طلبًا للانضمام إلى "حملة تشجير حدائق أحياء العاصمة" بصفة متطوع.',
    createdAt: "2026-09-21T10:05:00.000Z",
    href: "/dashboard/initiatives/init-06/applications",
    actorId: "usr-08",
    initiativeId: "init-06",
    applicationId: "app-10",
  },
  {
    id: "ntf-04",
    userId: "usr-01",
    type: "NEW_MESSAGE",
    title: "رسالة جديدة",
    message: "ياسين مرابط: السلام عليكم، متى تبدأ أنشطة المبادرة؟",
    createdAt: "2026-09-30T08:10:00.000Z",
    href: "/dashboard/messages/conv-01",
    actorId: "usr-02",
    initiativeId: "init-06",
    conversationId: "conv-01",
  },
  {
    id: "ntf-05",
    userId: "usr-01",
    type: "NEW_MESSAGE",
    title: "رسالة جديدة",
    message: "محمد الأمين قاسمي: أهلًا أمينة، هل يناسبك الحضور يوم السبت القادم لجلسة استشارة حول ترميم الواحات؟",
    createdAt: "2026-09-29T14:00:00.000Z",
    href: "/dashboard/messages/conv-03",
    actorId: "usr-06",
    initiativeId: "init-01",
    conversationId: "conv-03",
  },
  {
    id: "ntf-06",
    userId: "usr-01",
    type: "NEW_MESSAGE",
    title: "رسالة جديدة",
    message: "محمد الأمين قاسمي: نحتاج رأيك في اختيار المواقع ذات الأولوية.",
    createdAt: "2026-09-29T14:05:00.000Z",
    href: "/dashboard/messages/conv-03",
    actorId: "usr-06",
    initiativeId: "init-01",
    conversationId: "conv-03",
  },
  {
    id: "ntf-07",
    userId: "usr-01",
    type: "INITIATIVE_UPDATE",
    title: "تحديث في مبادرة تتابعينها",
    message: 'نشر منظمو "تنظيف وترميم واحات الوادي" موعد الحملة الميدانية القادمة.',
    createdAt: "2026-09-28T09:30:00.000Z",
    href: "/initiatives/init-01",
    actorId: "usr-06",
    initiativeId: "init-01",
  },
  {
    id: "ntf-08",
    userId: "usr-01",
    type: "APPLICATION_ACCEPTED",
    title: "تم قبول طلبك",
    message: 'تم قبول طلبك للانضمام إلى "تنظيف وترميم واحات الوادي" بصفة خبير / مستشار.',
    createdAt: "2026-06-12T11:30:00.000Z",
    readAt: "2026-06-12T18:00:00.000Z",
    href: "/dashboard/applications",
    actorId: "usr-06",
    initiativeId: "init-01",
    applicationId: "app-01",
  },
  {
    id: "ntf-09",
    userId: "usr-01",
    type: "APPLICATION_REJECTED",
    title: "تم رفض طلبك",
    message: 'تم رفض طلبك للانضمام إلى "دروس دعم مدرسي لأطفال الأحياء الشعبية". اطّلعي على سبب الرفض.',
    createdAt: "2026-05-02T12:00:00.000Z",
    readAt: "2026-05-02T20:15:00.000Z",
    href: "/dashboard/applications",
    actorId: "usr-03",
    initiativeId: "init-03",
    applicationId: "app-03",
  },
  {
    id: "ntf-10",
    userId: "usr-01",
    type: "NEW_MEMBER",
    title: "عضو جديد في فريقك",
    message: 'انضمت سارة بن يوسف إلى فريق "حملة تشجير حدائق أحياء العاصمة" بصفة خبير / مستشار.',
    createdAt: "2026-04-23T10:00:00.000Z",
    readAt: "2026-04-23T12:00:00.000Z",
    href: "/dashboard/initiatives/init-06/team",
    actorId: "usr-03",
    initiativeId: "init-06",
    applicationId: "app-17",
  },
  {
    id: "ntf-11",
    userId: "usr-01",
    type: "APPLICATION_WITHDRAWN",
    title: "تم سحب طلب انضمام",
    message: 'سحب عبد النور شريف طلبه للانضمام إلى "حملة تشجير حدائق أحياء العاصمة".',
    createdAt: "2026-05-04T09:00:00.000Z",
    readAt: "2026-05-04T10:30:00.000Z",
    href: "/dashboard/initiatives/init-06/applications",
    actorId: "usr-04",
    initiativeId: "init-06",
    applicationId: "app-16",
  },
  {
    id: "ntf-12",
    userId: "usr-01",
    type: "SYSTEM",
    title: "أكملي ملفك الشخصي",
    message: "إضافة مهاراتك واهتماماتك تساعد أصحاب المبادرات على التعرف على ما تستطيعين تقديمه.",
    createdAt: "2026-09-01T08:00:00.000Z",
    readAt: "2026-09-01T09:10:00.000Z",
    href: "/dashboard/profile",
  },
];
