import type { Wilaya } from "@/types";

/**
 * The 58 wilayas (provinces) of Algeria, including the 10 created in the
 * 2019 territorial reorganization. Static reference data — will eventually
 * live in a `Wilaya` table seeded once in the real database.
 */
export const wilayas: Wilaya[] = [
  { code: "01", slug: "adrar", name: "أدرار" },
  { code: "02", slug: "chlef", name: "الشلف" },
  { code: "03", slug: "laghouat", name: "الأغواط" },
  { code: "04", slug: "oum-el-bouaghi", name: "أم البواقي" },
  { code: "05", slug: "batna", name: "باتنة" },
  { code: "06", slug: "bejaia", name: "بجاية" },
  { code: "07", slug: "biskra", name: "بسكرة" },
  { code: "08", slug: "bechar", name: "بشار" },
  { code: "09", slug: "blida", name: "البليدة" },
  { code: "10", slug: "bouira", name: "البويرة" },
  { code: "11", slug: "tamanrasset", name: "تمنراست" },
  { code: "12", slug: "tebessa", name: "تبسة" },
  { code: "13", slug: "tlemcen", name: "تلمسان" },
  { code: "14", slug: "tiaret", name: "تيارت" },
  { code: "15", slug: "tizi-ouzou", name: "تيزي وزو" },
  { code: "16", slug: "alger", name: "الجزائر" },
  { code: "17", slug: "djelfa", name: "الجلفة" },
  { code: "18", slug: "jijel", name: "جيجل" },
  { code: "19", slug: "setif", name: "سطيف" },
  { code: "20", slug: "saida", name: "سعيدة" },
  { code: "21", slug: "skikda", name: "سكيكدة" },
  { code: "22", slug: "sidi-bel-abbes", name: "سيدي بلعباس" },
  { code: "23", slug: "annaba", name: "عنابة" },
  { code: "24", slug: "guelma", name: "قالمة" },
  { code: "25", slug: "constantine", name: "قسنطينة" },
  { code: "26", slug: "medea", name: "المدية" },
  { code: "27", slug: "mostaganem", name: "مستغانم" },
  { code: "28", slug: "msila", name: "المسيلة" },
  { code: "29", slug: "mascara", name: "معسكر" },
  { code: "30", slug: "ouargla", name: "ورقلة" },
  { code: "31", slug: "oran", name: "وهران" },
  { code: "32", slug: "el-bayadh", name: "البيض" },
  { code: "33", slug: "illizi", name: "إليزي" },
  { code: "34", slug: "bordj-bou-arreridj", name: "برج بوعريريج" },
  { code: "35", slug: "boumerdes", name: "بومرداس" },
  { code: "36", slug: "el-tarf", name: "الطارف" },
  { code: "37", slug: "tindouf", name: "تندوف" },
  { code: "38", slug: "tissemsilt", name: "تسمسيلت" },
  { code: "39", slug: "el-oued", name: "الوادي" },
  { code: "40", slug: "khenchela", name: "خنشلة" },
  { code: "41", slug: "souk-ahras", name: "سوق أهراس" },
  { code: "42", slug: "tipaza", name: "تيبازة" },
  { code: "43", slug: "mila", name: "ميلة" },
  { code: "44", slug: "ain-defla", name: "عين الدفلى" },
  { code: "45", slug: "naama", name: "النعامة" },
  { code: "46", slug: "ain-temouchent", name: "عين تموشنت" },
  { code: "47", slug: "ghardaia", name: "غرداية" },
  { code: "48", slug: "relizane", name: "غليزان" },
  { code: "49", slug: "timimoun", name: "تيميمون" },
  { code: "50", slug: "bordj-badji-mokhtar", name: "برج باجي مختار" },
  { code: "51", slug: "ouled-djellal", name: "أولاد جلال" },
  { code: "52", slug: "beni-abbes", name: "بني عباس" },
  { code: "53", slug: "in-salah", name: "عين صالح" },
  { code: "54", slug: "in-guezzam", name: "عين قزام" },
  { code: "55", slug: "touggourt", name: "تقرت" },
  { code: "56", slug: "djanet", name: "جانت" },
  { code: "57", slug: "el-mghair", name: "المغير" },
  { code: "58", slug: "el-meniaa", name: "المنيعة" },
];
